name: india_air_quality_json

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        run: |
          pip install --upgrade pip
          pip install "snowflake-snowpark-python[pandas]"

      - name: Run ingestion script
        run: python ingest-api-data.py
