name: india_air_quality_json

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python and install dependencies
        run: |
          echo "Current directory: $(pwd)"
          echo "Installing pip and dependencies..."
          pip install --upgrade pip
          pip install "snowflake-snowpark-python[pandas]"

      - name: Run ingestion script
        run: |
          echo "Running ingestion script..."
          python ingest-api-data.py
